### ISSUE TITLE
Error loading VPA view with ReadStatisticsFromData enabled: The specified Power BI workspace is not found.

### ISSUE THREAD

**Issue by Arklur** [DaxStudio/DaxStudio#1005]
**Describe the bug**
I connect to a (PPU) workspace, but when I click on Advanced > View Metrics, I got both a warning and an error, see image below.

**To Reproduce**
1. Connect to a dataset on a (PPU) workspace
2. Click on 'Advanced'
3. Click on 'View Metrics'

**Expected behavior**
I get the tables of metrics.

**Screenshots**
![image](https://user-images.githubusercontent.com/9089026/206262569-b2514b63-6715-40fa-a19c-4a67625463ac.png)

**Additional context**
I have version 3.0.5.

This is what I see in the log file:
```
2022-12-07 19:08:53.392 +01:00 [WRN] DocumentViewModel ViewAnalysisDataAsync Error loading VPA view with ReadStatisticsFromData enabled: The specified Power BI workspace is not found.

Technical Details:
RootActivityId: 2f9f20fc-9c66-4d76-bf94-68d6945032ca
Microsoft.AnalysisServices.ConnectionException: The specified Power BI workspace is not found.

Technical Details:
RootActivityId: 2f9f20fc-9c66-4d76-bf94-68d6945032ca
   at Microsoft.AnalysisServices.ConnectionInfo.ResolveHTTPConnectionPropertiesForPaaSInfrastructure(IConnectivityOwner owner, Uri& dataSourceUri, Boolean acquireAADToken, Boolean returnCloudConnectionAuthenticationProperties, String& paasCoreServerName, CloudConnectionAuthenticationProperties& cloudConnectionAuthenticationProperties)
   at Microsoft.AnalysisServices.HttpStream.Create(IConnectivityOwner owner, ConnectionInfo info, XmlaDataType desiredRequestType, XmlaDataType desiredResponseType, Int32 readTimeout, Boolean& isSessionTokenNeeded)
   at Microsoft.AnalysisServices.XmlaClient.OpenHttpConnection(ConnectionInfo connectionInfo, Boolean& isSessionTokenNeeded)
   at Microsoft.AnalysisServices.XmlaClient.OpenConnectionAndCheckIfSessionTokenNeeded(ConnectionInfo connectionInfo)
   at Microsoft.AnalysisServices.XmlaClient.OpenConnection(ConnectionInfo connectionInfo, Boolean& isSessionTokenNeeded)
   at Microsoft.AnalysisServices.XmlaClient.Connect(ConnectionInfo connectionInfo, Boolean beginSession)
   at Microsoft.AnalysisServices.Core.Server.Connect(String connectionString, String sessionId, ObjectExpansion expansionType)
   at Microsoft.AnalysisServices.Core.Server.Connect(String connectionString)
   at Dax.Metadata.Extractor.TomExtractor.GetDatabase(String serverName, String databaseName)
   at Dax.Metadata.Extractor.TomExtractor.GetDaxModel(String serverName, String databaseName, String applicationName, String applicationVersion, Boolean readStatisticsFromData, Int32 sampleRows, Boolean analyzeDirectQuery)
   at DaxStudio.UI.ViewModels.DocumentViewModel.<>c__DisplayClass440_0.<ViewAnalysisDataAsync>b__0()
2022-12-07 19:08:53.507 +01:00 [ERR] DocumentViewModel ViewAnalysisData Error Getting Metrics
Microsoft.AnalysisServices.ConnectionException: The specified Power BI workspace is not found.

Technical Details:
RootActivityId: 92bbde91-de15-4c6d-99ee-fc4c82fc079d
   at Microsoft.AnalysisServices.ConnectionInfo.ResolveHTTPConnectionPropertiesForPaaSInfrastructure(IConnectivityOwner owner, Uri& dataSourceUri, Boolean acquireAADToken, Boolean returnCloudConnectionAuthenticationProperties, String& paasCoreServerName, CloudConnectionAuthenticationProperties& cloudConnectionAuthenticationProperties)
   at Microsoft.AnalysisServices.HttpStream.Create(IConnectivityOwner owner, ConnectionInfo info, XmlaDataType desiredRequestType, XmlaDataType desiredResponseType, Int32 readTimeout, Boolean& isSessionTokenNeeded)
   at Microsoft.AnalysisServices.XmlaClient.OpenHttpConnection(ConnectionInfo connectionInfo, Boolean& isSessionTokenNeeded)
   at Microsoft.AnalysisServices.XmlaClient.OpenConnectionAndCheckIfSessionTokenNeeded(ConnectionInfo connectionInfo)
   at Microsoft.AnalysisServices.XmlaClient.OpenConnection(ConnectionInfo connectionInfo, Boolean& isSessionTokenNeeded)
   at Microsoft.AnalysisServices.XmlaClient.Connect(ConnectionInfo connectionInfo, Boolean beginSession)
   at Microsoft.AnalysisServices.Core.Server.Connect(String connectionString, String sessionId, ObjectExpansion expansionType)
   at Microsoft.AnalysisServices.Core.Server.Connect(String connectionString)
   at Dax.Metadata.Extractor.TomExtractor.GetDatabase(String serverName, String databaseName)
   at Dax.Metadata.Extractor.TomExtractor.GetDaxModel(String serverName, String databaseName, String applicationName, String applicationVersion, Boolean readStatisticsFromData, Int32 sampleRows, Boolean analyzeDirectQuery)
   at DaxStudio.UI.ViewModels.DocumentViewModel.<>c__DisplayClass440_0.<ViewAnalysisDataAsync>b__0()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DaxStudio.UI.ViewModels.DocumentViewModel.<ViewAnalysisDataAsync>d__440.MoveNext()
```

If I turn off the "Read statistics from data" in the Advanced Settings (in the VertiPaq Analyzer box), I only get an error but no warning.

**Comment by dgosbell** [comment]
Are there any characters in your workspace name that are not letters or numbers? I cannot reproduce this so I'm not sure what is triggering this. Is your model using anything like direct query, aggregations, hybrid tables or anything like that or is it a straight import mode model?

**Comment by Arklur** [comment]
The name of the workspace is **VpkSandboxPPU**. As for the model, it's just - as the name suggests - a demo one, a single table in it with incremental refresh (...and 2 LocalDateTable :O).

Here is the "Model.bim" content of the model.
[Issue_1005.txt](https://github.com/DaxStudio/DaxStudio/files/10211375/Issue_1005.txt)

I can't think of anything special about the model.

**Comment by Arklur** [comment]
Actually, something that come into my mind. 

We are working for a project and we are external users, so, for example, when we try to access the workspace there, we need to "switch" to the specific organization in order to get the workspace we want. The gist of it is in [this Guy in a Cube video](https://www.youtube.com/watch?v=x1xMxRXQ2So&ab_channel=GuyinaCube) (you probably familiar with this, but for the sake of completeness, putting this here, might be helpful for others too?).

Now obviously there is no issue connecting to the workspace and query the data, based on the error message, can it be that behind the curtains the program tries to connect again to the workspace/model, but it gets lost (I really can't phrase this better) and not using the right credentials?...

**Comment by dgosbell** [comment]
OK thanks for this. The external user connection is probably the source of this issue. I'll need to see if I can set something like this up so that I can do some tests and figure out why this is happening. The view metrics feature will attempt to open a new connection, but I would have thought it should have used the access token from the existing connection.

**Comment by Arklur** [comment]
Another thing I've just found out is that after my session expires (?), when I try to reconnect to the same workspace, I get the same error ("The specified Power BI workspace is not found"). 

It seems the only way to connect back again is to restart the program.
