### ISSUE TITLE
Dax Studio showing Access Denied in Excel but opens in Power BI

### ISSUE THREAD

**Issue by Newboy1975** [DaxStudio/DaxStudio#1192]
As the title says, it opens in PowerBI but not in Excel  log below  for a clean sheet: AV isn't showing any issues apparenlty, as I have seen in other posts that causes an issue.

2023-10-17 13:48:38.812 +02:00 [INF] Logging enabled by Shift Key at startup
2023-10-17 13:48:39.230 +02:00 [DBG] DaxStudioRibbon RibbonLoad Start
2023-10-17 13:48:39.477 +02:00 [DBG] DaxStudioRibbon RibbonLoad Finish
2023-10-17 13:48:50.977 +02:00 [DBG] DaxStudioRibbon Launch Entering Launch()
2023-10-17 13:48:51.310 +02:00 [INF] WebHost Start DaxStudio Host starting on port 9000
2023-10-17 13:48:53.109 +02:00 [DBG] Startup Configuration Starting OWIN configuration
2023-10-17 13:48:53.938 +02:00 [DBG] Startup Configuration Finished OWIN configuration
2023-10-17 13:48:53.988 +02:00 [INF] WebHost Start DaxStudio Host started on port 9000
2023-10-17 13:48:53.989 +02:00 [DBG] DaxStudioRibbon Launch Checking for an existing instance of DaxStudio.exe
2023-10-17 13:48:54.019 +02:00 [DBG] DaxStudioRibbon BtnDaxClick About to launch DaxStudio on path: C:\Program Files\DAX Studio\daxstudio.exe port: 9000
2023-10-17 13:48:56.380 +02:00 [ERR] DaxStudioRibbon BtnDaxClick Access is denied    at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at DaxStudio.ExcelAddin.DaxStudioRibbon.Launch(Boolean enableLogging)
   at DaxStudio.ExcelAddin.DaxStudioRibbon.BtnDaxClick(Object sender, RibbonControlEventArgs e)
System.ComponentModel.Win32Exception (0x80004005): Access is denied
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at DaxStudio.ExcelAddin.DaxStudioRibbon.Launch(Boolean enableLogging)
   at DaxStudio.ExcelAddin.DaxStudioRibbon.BtnDaxClick(Object sender, RibbonControlEventArgs e)
2023-10-17 13:48:58.149 +02:00 [INF] ============ Excel Add-in Shutdown =============
2023-10-17 13:48:58.153 +02:00 [DBG] DaxStudioRibbon DaxStudioRibbon_Close Entering
2023-10-17 13:48:58.154 +02:00 [INF] DaxStudio Host stopped listening on port 9000
2023-10-17 13:48:58.166 +02:00 [DBG] DaxStudioRibbon DaxStudioRibbon_Close Exiting

**Comment by dgosbell** [comment]
Unfortunately, if this is not an AV issue then this is likely to be a security policy deployed by your IT department. There is not much I can do from a DAX Studio side to circumvent security policies set on your machine. (if there was a way around permissions issues like this all the virus writers would use them). I might be able to improve the discoverability of the Excel addin so that you can possibly connect when launching DAX Studio separately. But I'll need to do some experimenting to see if I can make that work.

**Comment by Newboy1975** [comment]
Thanks @dgosbell  it looks like the new MIcrosoft Base line security we applied a while ago has blocked it.  If removed the addin works ok (however it keeps needing renabled, but I'll do some searching on here for fixes.  

Thanks for the reply.
