### ISSUE TITLE
Excel (MS Office 365 Pro Plus) Get Data crashes when Dax Studio is installed on PC (with or without excel add-in)

### ISSUE THREAD

**Issue by mgandulfo** [DaxStudio/DaxStudio#173]
Every time I try to get data from Salesforce through Excel, when I select an object or report and click Load, I get the following error:  Unexpected Error: Something went wrong...... (see details below).

I have tried uninstalling Dax Studio and reinstalling without selecting the excel add-in but get the same result. This used to happen with previous and with current version of dax studio. (updated today).

I hope you can look into it.

Error dump details below:

Feedback Type:
Frown (Error)

Error Message:
Object reference not set to an instance of an object.

Stack Trace:
   at Microsoft.Mashup.Client.UI.Windows.JsHostedScript.<>c__DisplayClass4.<InvokeScript>b__3()
   at Microsoft.Mashup.Client.UI.Windows.JsErrorHandler.WrapInvokeScript(Func`1 invokeScript)
   at Microsoft.Mashup.Client.UI.Windows.JsHostedScript.InvokeScript(String script, Boolean bypassDebugHost)
   at Microsoft.Mashup.Client.UI.Windows.JsHostedScript.TryInvoke[T](String script, T& result)
   at Microsoft.Mashup.Client.UI.Windows.JsHostedScript.TryInvoke(String script)
   at Microsoft.Mashup.Client.UI.Shared.Ux.Navigator.QueryNavigatorInvocationHost.UnbindEventHandlers()
   at Microsoft.Mashup.Client.UI.Shared.Ux.FloatingDialog.NavigatorFloatingDialog.Dispose(Boolean disposing)
   at Microsoft.Mashup.Client.UI.Shared.TestUtilities.InfiniteLifetimeOleMarshalObject.Dispose()
   at Microsoft.Mashup.Client.UI.Shared.Ux.FloatingDialog.NavigatorFloatingDialog.ShowEditLoadTo(IWindowHandle owner, IUIHost uiHost, Query query, ITelemetryService telemetryService, ITeachingCalloutManager teachingCalloutManager)
   at Microsoft.Mashup.Client.Excel.ExcelDataImporter.<>c__DisplayClass1c.<ShowNavigator>b__1b(IWorkbook workbook)
   at Microsoft.Mashup.Client.Excel.ExcelDataImporter.<>c__DisplayClassa.<>c__DisplayClassc.<NotifyGetDataPresence>b__9()
   at Microsoft.Mashup.Client.Excel.Shim.NativeCoAuthServices.NotifyGetDataPresence(IWorkbook workbook, Action action)
   at Microsoft.Mashup.Client.Excel.ExcelDataImporter.<>c__DisplayClassa.<NotifyGetDataPresence>b__8(IWorkbook workbook)
   at Microsoft.Mashup.Client.Excel.ExcelDataImporter.<>c__DisplayClassf.<InvokeOnWorkbook>b__e(IWorkbook workbook, IWindowContext windowContext)
   at Microsoft.Mashup.Client.Excel.ExcelDataImporter.InvokeOnWorkbook[T](Func`3 action, T defaultValue)
   at Microsoft.Mashup.Client.Excel.ExcelDataImporter.InvokeOnWorkbook(Action`1 action)
   at Microsoft.Mashup.Client.Excel.ExcelDataImporter.NotifyGetDataPresence(Action`1 action)
   at Microsoft.Mashup.Client.Excel.ExcelDataImporter.ShowNavigator(Query query)
   at Microsoft.Mashup.Client.UI.Shared.DataImporter.ShowNavigatorOnSourceQuery(Query query, IEnumerable`1& importedQueries)
   at Microsoft.Mashup.Client.UI.Shared.DataImporter.ImportNavigationSource(Query query)
   at Microsoft.Mashup.Client.UI.Shared.DataImporter.OnGetPreviewResult(PreviewResult preview, Query query, String sourceID, String formulaTitle, Nullable`1 explicitImportDestination, Boolean isNewQuery, Boolean isFromEditor)
   at Microsoft.Mashup.Client.UI.Shared.DataImporter.GetPreviewResult(Query query, String sourceID, String formulaTitle, Boolean isNewQuery, Boolean isFromEditor, Nullable`1 explicitImportDestination)
   at Microsoft.Mashup.Client.Excel.ExcelDataImporter.<>c__DisplayClass20.<GetPreviewResult>b__1f()
   at Microsoft.Mashup.Client.Excel.Shim.NativeWorkbookStorageServices.Microsoft.Mashup.Client.Excel.Shim.IDeferredStorageInvoker.InvokeDeferredStorageAction(IWorkbook workbook, Action action)
   at Microsoft.Mashup.Client.Excel.Shim.NativeCoAuthServices.InvokeCoauthAction(IWorkbook workbook, UndoableActionType actionType, Action action)
   at Microsoft.Mashup.Client.Excel.ExcelDataImporter.<>c__DisplayClass20.<GetPreviewResult>b__1e(IWorkbook workbook)
   at Microsoft.Mashup.Client.Excel.ExcelDataImporter.<>c__DisplayClassa.<>c__DisplayClassc.<NotifyGetDataPresence>b__9()
   at Microsoft.Mashup.Client.Excel.Shim.NativeCoAuthServices.NotifyGetDataPresence(IWorkbook workbook, Action action)
   at Microsoft.Mashup.Client.Excel.ExcelDataImporter.<>c__DisplayClassa.<NotifyGetDataPresence>b__8(IWorkbook workbook)
   at Microsoft.Mashup.Client.Excel.ExcelDataImporter.<>c__DisplayClassf.<InvokeOnWorkbook>b__e(IWorkbook workbook, IWindowContext windowContext)
   at Microsoft.Mashup.Client.Excel.ExcelDataImporter.InvokeOnWorkbook[T](Func`3 action, T defaultValue)
   at Microsoft.Mashup.Client.Excel.ExcelDataImporter.InvokeOnWorkbook(Action`1 action)
   at Microsoft.Mashup.Client.Excel.ExcelDataImporter.NotifyGetDataPresence(Action`1 action)
   at Microsoft.Mashup.Client.Excel.ExcelDataImporter.GetPreviewResult(Query query, String sourceID, String formulaTitle, Boolean isNewQuery, Boolean isFromEditor, Nullable`1 explicitImportDestination)
   at Microsoft.Mashup.Client.UI.Shared.DataImporter.<>c__DisplayClass20.<OnQuerySettingsResolved>b__1d()
   at Microsoft.Mashup.Host.Document.ExceptionHandlerExtensions.HandleExceptions(IExceptionHandler exceptionHandler, Action action)

Stack Trace Message:
Object reference not set to an instance of an object.

Invocation Stack Trace:
   at Microsoft.Mashup.Host.Document.ExceptionExtensions.GetCurrentInvocationStackTrace()
   at Microsoft.Mashup.Client.UI.Shared.StackTraceInfo..ctor(String exceptionStackTrace, String invocationStackTrace, String exceptionMessage)
   at Microsoft.Mashup.Client.UI.Shared.FeedbackErrorInfo..ctor(String message, Exception exception, Nullable`1 stackTraceInfo)
   at Microsoft.Mashup.Client.Excel.Native.NativeUserFeedbackServices.ReportException(IWindowHandle activeWindow, IUIHost uiHost, FeedbackPackageInfo feedbackPackageInfo, Exception e, Boolean useGDICapture)
   at Microsoft.Mashup.Client.UI.Shared.UnexpectedExceptionHandler.<>c__DisplayClass1.<HandleException>b__0()
   at Microsoft.Mashup.Host.Document.SynchronizationContextExtensions.SendAndMarshalExceptions(SynchronizationContext context, Action callback)
   at Microsoft.Mashup.Client.UI.Shared.UnexpectedExceptionHandler.HandleException(Exception e)
   at Microsoft.Mashup.Host.Document.ExceptionHandlerExtensions.HandleExceptions(IExceptionHandler exceptionHandler, Action action)
   at Microsoft.Mashup.Host.Document.SynchronizationContextExtensions.<>c__DisplayClassf.<Post>b__e(Object null)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Supports Premium Content:
True

Formulas:

section Section1;

shared #"NavigatorBase_6912edf7-596b-44bf-9aec-200aca3df677" = let
    Source = Salesforce.Reports()
in
    Source;

**Comment by dgosbell** [comment]
Sorry, but I do not believe this error has anything to do with DAX Studio at all.

Our addin is only active when you click the button to launch the user interface. We don't have any code at all that attempts to connect in any way with the "Get Data" functionality. And until you click the DAX Studio button our addin is completely passive, not running any code.

You can see in the stack trace that all the calls either start with "System" or  "Microsoft.Mashup". This looks like a pure Power Query error. 

If you completely uninstall DAX Studio does this fix your issue or does it still persist?

**Comment by mgandulfo** [comment]
Thanks for your prompt reply. I'll investigate and get back to you.

**Comment by dgosbell** [comment]
Closing this issue - if you do have more information to add feel free to re-open this or raise a new issue
