### ISSUE TITLE
An Item with Same Key has already been added

### ISSUE THREAD

**Issue by asinanan** [DaxStudio/DaxStudio#260]
This issues happens with any Pbi file that i attempt to connect to using Dax studio.
I have tried re-installing and also your clear config.bat scripts but nothing seems to solve this.

Within the Output window two results are shown
-Established Connection
-An Item with the same key has already been added.

Error
![DAX_studio issue](https://user-images.githubusercontent.com/32080773/69921207-1a9fca00-14e4-11ea-80a8-7a0dc49480f6.PNG)

DAX studio Version
![DAX_studio version](https://user-images.githubusercontent.com/32080773/69921245-520e7680-14e4-11ea-9c86-431dbba80b8b.PNG)

Log File
`2018-06-25 13:27:32.075 +10:00 [Error] "DocumentViewModel" "HasDatabaseSchemaChanged" "The connection either timed out or was lost." "   at Microsoft.AnalysisServices.AdomdClient.XmlaClient.SendMessage(Boolean endReceivalIfException, Boolean readSession, Boolean readNamespaceCompatibility)
   at Microsoft.AnalysisServices.AdomdClient.AdomdConnection.XmlaClientProvider.Microsoft.AnalysisServices.AdomdClient.AdomdConnection.IXmlaClientProviderEx.Discover(String requestType, String requestNamespace, IDictionary restrictions, InlineErrorHandlingType inlineErrorHandling, IDictionary requestProperties)
   at Microsoft.AnalysisServices.AdomdClient.AdomdConnection.GetSchemaDataSet(String schemaName, String schemaNamespace, IDictionary adomdRestrictions, Boolean throwOnInlineErrors, IDictionary requestProperties)
   at Microsoft.AnalysisServices.AdomdClient.AdomdConnection.GetSchemaDataSet(String schemaName, String schemaNamespace, AdomdRestrictionCollection restrictions, Boolean throwOnInlineErrors, AdomdPropertyCollection requestProperties)
   at Microsoft.AnalysisServices.AdomdClient.AdomdConnection.GetSchemaDataSet(String schemaName, AdomdRestrictionCollection restrictions, Boolean throwOnInlineErrors)
   at ADOTabular.AdomdClientWrappers.AdomdConnection.GetSchemaDataSet(String schemaName, AdomdRestrictionCollection restrictions, Boolean throwOnInlineErrors)
   at ADOTabular.ADOTabularDatabaseCollection.GetDatabaseDictionaryFromXML()
   at ADOTabular.ADOTabularDatabaseCollection.GetDatabaseDictionary(Int32 spid, Boolean refresh)
   at ADOTabular.ADOTabularDatabase.HasSchemaChanged()
   at DaxStudio.UI.ViewModels.DocumentViewModel.HasDatabaseSchemaChanged()"`

**Comment by dgosbell** [comment]
Are you able to upload an example pbix file that triggers this error? It does not need to have any real data, the issue is probably related to the model structure or object names.

That error log does not relate to that error message and none of the pbix files I have to exhibit this issue.

**Comment by dgosbell** [comment]
Closing due to lack of response
