### ISSUE TITLE
Error Connecting : Unable to connect to the remote server

### ISSUE THREAD

**Issue by ElMiguel123** [DaxStudio/DaxStudio#389]
Good morning,

We try using DaxStudio to access an AS Instance.
For the access we must use a proxy (enterprise) but there are no way to access the server. Each time we check the log, it says the following message :

2020-07-27 10:41:17.651 +02:00 [Error] "DocumentViewModel" "Handle(ConnectEvent message)" "Unable to connect to the remote server"
Microsoft.AnalysisServices.AdomdClient.AdomdConnectionException: Unable to connect to the remote server ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond xxx.xxx.xxx.xxx:8000
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)

The "xxx.xxx.xxx.xxx:8000" is our proxy. The port 8000 is close and cannot be open (security reason). Only the port 8080 is allowed. 

Is there a way to correct that ? a config file ? A bug ?

Nota: I've done the test with the current and latest version of DAxstudio, same behavior.

**Comment by dgosbell** [comment]
Can you describe your configuration in a bit more detail? What sort of proxy are you using? I've only ever used IIS and msmdpump.dll as a proxy in front of SSAS, but it does not look like you are using a http(s):// connection.

Are you able to connect from other tools like SSMS, Power BI Desktop or Excel?

Do you know where the request for port 8000 is coming from? This is not a standard SSAS port, there is nothing in DAX Studio that would be trying to redirect to this port.

Are you able to start up DAX Studio with the [diagnostic logging](https://daxstudio.org/documentation/troubleshooting/logging-settings/) enabled, then try to connect to your server and then close DAX Studio and upload a copy of that log to the Github issue?

**Comment by ElMiguel123** [comment]
Good afternoon and thanks for your follow-up.

PowerBI Desktop, SSMS run smoothly without any issue
The Dax Studio I've got on my workstation (same behavior with oldest version) is 2.11.2

When I run Fiddler on my computer to track the network traffic I see no connection at all except when I launch the application which is really weird.

```
#	Result	Protocol	Host	URL	Body	Caching	Content-Type	Process	Comments	Custom	
1	200	HTTP	Tunnel to	raw.githubusercontent.com:443	0			daxstudio:27964			
4	200	HTTPS	raw.githubusercontent.com	/DaxStudio/DaxStudio/master/src/CurrentReleaseVersion.json	196	max-age=300; Expires: Mon, 27 Jul 2020 13:02:13 GMT	text/plain; charset=utf-8	daxstudio:27964			
5	200	HTTP	Tunnel to	www.daxformatter.com:443	0			daxstudio:27964			
6	301	HTTPS	www.daxformatter.com	/api/daxformatter/DaxTextFormat	189		text/html; charset=UTF-8	daxstudio:27964	
```		

I didn't see something block on our antivirus (Symantec) 

In attachment the log generate by the Dax Studio

2020-07-27 10:37:13.699 +02:00 [Error] "DocumentViewModel" "Handle(ConnectEvent message)" "Unable to connect to the remote server"
Microsoft.AnalysisServices.AdomdClient.AdomdConnectionException: Unable to connect to the remote server ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 172.20.187.115:8000
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at Microsoft.AnalysisServices.AdomdClient.ASAzureUtility.PostHttpJsonData[TRequest,TResult](Uri uri, Dictionary`2 headers, TRequest requestObject, Int32 timeoutMs)
   at Microsoft.AnalysisServices.AdomdClient.ASAzureUtility.ResolvePaaSConnectionEndpointDetail(AsInstanceType asInstanceType, Uri dataSourceUri, String paasInfrastructureServerName, String restrictDatabaseName, Boolean premiumPublicXmlaEndpoint, TimeLeft& timeLeft, OnTimeoutAction timeoutAction, Guid parentActivityId)
   --- End of inner exception stack trace ---
   at Microsoft.AnalysisServices.AdomdClient.ASAzureUtility.ThrowConnectionException(WebException ex, AsInstanceType asInstanceType)
   at Microsoft.AnalysisServices.AdomdClient.ASAzureUtility.ResolvePaaSConnectionEndpointDetail(AsInstanceType asInstanceType, Uri dataSourceUri, String paasInfrastructureServerName, String restrictDatabaseName, Boolean premiumPublicXmlaEndpoint, TimeLeft& timeLeft, OnTimeoutAction timeoutAction, Guid parentActivityId)
   at Microsoft.AnalysisServices.AdomdClient.ConnectionInfo.ResolveHTTPConnectionPropertiesForPaaSInfrastructure(IConnectivityOwner owner, Uri& dataSourceUri, Boolean acquireAADToken, Boolean returnCloudConnectionAuthenticationProperties, String& paasCoreServerName, CloudConnectionAuthenticationProperties& cloudConnectionAuthenticationProperties)
   at Microsoft.AnalysisServices.AdomdClient.XmlaClient.OpenHttpConnection(ConnectionInfo connectionInfo, Boolean& isSessionTokenNeeded)
   at Microsoft.AnalysisServices.AdomdClient.XmlaClient.OpenConnection(ConnectionInfo connectionInfo, Boolean& isSessionTokenNeeded)
   at Microsoft.AnalysisServices.AdomdClient.XmlaClient.Connect(ConnectionInfo connectionInfo, Boolean beginSession)
   at Microsoft.AnalysisServices.AdomdClient.AdomdConnection.XmlaClientProvider.Connect(Boolean toIXMLA)
   at Microsoft.AnalysisServices.AdomdClient.AdomdConnection.ConnectToXMLA(Boolean createSession, Boolean isHTTP)
   at Microsoft.AnalysisServices.AdomdClient.AdomdConnection.Open()
   at ADOTabular.ADOTabularConnection.Open()
   at DaxStudio.UI.ViewModels.DocumentViewModel.SetupConnection(ConnectEvent message, ADOTabularConnection cnn)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback)
   at DaxStudio.UI.ViewModels.DocumentViewModel.<>c__DisplayClass263_0.<Handle>b__0()
   at System.Threading.Tasks.Task.Execute()
2020-07-27 10:40:57.239 +02:00 [Error] "DocumentViewModel" "Handle(ConnectEvent message)" "Unable to connect to the remote server"
Microsoft.AnalysisServices.AdomdClient.AdomdConnectionException: Unable to connect to the remote server ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 172.20.187.115:8000
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at Microsoft.AnalysisServices.AdomdClient.ASAzureUtility.PostHttpJsonData[TRequest,TResult](Uri uri, Dictionary`2 headers, TRequest requestObject, Int32 timeoutMs)
   at Microsoft.AnalysisServices.AdomdClient.ASAzureUtility.ResolvePaaSConnectionEndpointDetail(AsInstanceType asInstanceType, Uri dataSourceUri, String paasInfrastructureServerName, String restrictDatabaseName, Boolean premiumPublicXmlaEndpoint, TimeLeft& timeLeft, OnTimeoutAction timeoutAction, Guid parentActivityId)
   --- End of inner exception stack trace ---
   at Microsoft.AnalysisServices.AdomdClient.ASAzureUtility.ThrowConnectionException(WebException ex, AsInstanceType asInstanceType)
   at Microsoft.AnalysisServices.AdomdClient.ASAzureUtility.ResolvePaaSConnectionEndpointDetail(AsInstanceType asInstanceType, Uri dataSourceUri, String paasInfrastructureServerName, String restrictDatabaseName, Boolean premiumPublicXmlaEndpoint, TimeLeft& timeLeft, OnTimeoutAction timeoutAction, Guid parentActivityId)
   at Microsoft.AnalysisServices.AdomdClient.ConnectionInfo.ResolveHTTPConnectionPropertiesForPaaSInfrastructure(IConnectivityOwner owner, Uri& dataSourceUri, Boolean acquireAADToken, Boolean returnCloudConnectionAuthenticationProperties, String& paasCoreServerName, CloudConnectionAuthenticationProperties& cloudConnectionAuthenticationProperties)
   at Microsoft.AnalysisServices.AdomdClient.XmlaClient.OpenHttpConnection(ConnectionInfo connectionInfo, Boolean& isSessionTokenNeeded)
   at Microsoft.AnalysisServices.AdomdClient.XmlaClient.OpenConnection(ConnectionInfo connectionInfo, Boolean& isSessionTokenNeeded)
   at Microsoft.AnalysisServices.AdomdClient.XmlaClient.Connect(ConnectionInfo connectionInfo, Boolean beginSession)
   at Microsoft.AnalysisServices.AdomdClient.AdomdConnection.XmlaClientProvider.Connect(Boolean toIXMLA)
   at Microsoft.AnalysisServices.AdomdClient.AdomdConnection.ConnectToXMLA(Boolean createSession, Boolean isHTTP)
   at Microsoft.AnalysisServices.AdomdClient.AdomdConnection.Open()
   at ADOTabular.ADOTabularConnection.Open()
   at DaxStudio.UI.ViewModels.DocumentViewModel.SetupConnection(ConnectEvent message, ADOTabularConnection cnn)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback)
   at DaxStudio.UI.ViewModels.DocumentViewModel.<>c__DisplayClass263_0.<Handle>b__0()
   at System.Threading.Tasks.Task.Execute()
2020-07-27 10:41:17.651 +02:00 [Error] "DocumentViewModel" "Handle(ConnectEvent message)" "Unable to connect to the remote server"
Microsoft.AnalysisServices.AdomdClient.AdomdConnectionException: Unable to connect to the remote server ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 172.20.187.115:8000
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at Microsoft.AnalysisServices.AdomdClient.ASAzureUtility.PostHttpJsonData[TRequest,TResult](Uri uri, Dictionary`2 headers, TRequest requestObject, Int32 timeoutMs)
   at Microsoft.AnalysisServices.AdomdClient.ASAzureUtility.ResolvePaaSConnectionEndpointDetail(AsInstanceType asInstanceType, Uri dataSourceUri, String paasInfrastructureServerName, String restrictDatabaseName, Boolean premiumPublicXmlaEndpoint, TimeLeft& timeLeft, OnTimeoutAction timeoutAction, Guid parentActivityId)
   --- End of inner exception stack trace ---
   at Microsoft.AnalysisServices.AdomdClient.ASAzureUtility.ThrowConnectionException(WebException ex, AsInstanceType asInstanceType)
   at Microsoft.AnalysisServices.AdomdClient.ASAzureUtility.ResolvePaaSConnectionEndpointDetail(AsInstanceType asInstanceType, Uri dataSourceUri, String paasInfrastructureServerName, String restrictDatabaseName, Boolean premiumPublicXmlaEndpoint, TimeLeft& timeLeft, OnTimeoutAction timeoutAction, Guid parentActivityId)
   at Microsoft.AnalysisServices.AdomdClient.ConnectionInfo.ResolveHTTPConnectionPropertiesForPaaSInfrastructure(IConnectivityOwner owner, Uri& dataSourceUri, Boolean acquireAADToken, Boolean returnCloudConnectionAuthenticationProperties, String& paasCoreServerName, CloudConnectionAuthenticationProperties& cloudConnectionAuthenticationProperties)
   at Microsoft.AnalysisServices.AdomdClient.XmlaClient.OpenHttpConnection(ConnectionInfo connectionInfo, Boolean& isSessionTokenNeeded)
   at Microsoft.AnalysisServices.AdomdClient.XmlaClient.OpenConnection(ConnectionInfo connectionInfo, Boolean& isSessionTokenNeeded)
   at Microsoft.AnalysisServices.AdomdClient.XmlaClient.Connect(ConnectionInfo connectionInfo, Boolean beginSession)
   at Microsoft.AnalysisServices.AdomdClient.AdomdConnection.XmlaClientProvider.Connect(Boolean toIXMLA)
   at Microsoft.AnalysisServices.AdomdClient.AdomdConnection.ConnectToXMLA(Boolean createSession, Boolean isHTTP)
   at Microsoft.AnalysisServices.AdomdClient.AdomdConnection.Open()
   at ADOTabular.ADOTabularConnection.Open()
   at DaxStudio.UI.ViewModels.DocumentViewModel.SetupConnection(ConnectEvent message, ADOTabularConnection cnn)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback)
   at DaxStudio.UI.ViewModels.DocumentViewModel.<>c__DisplayClass263_0.<Handle>b__0()
   at System.Threading.Tasks.Task.Execute()
2020-07-27 13:24:55.563 +02:00 [Error] "DocumentViewModel" "Handle(ConnectEvent message)" "Unable to connect to the remote server"
Microsoft.AnalysisServices.AdomdClient.AdomdConnectionException: Unable to connect to the remote server ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 172.20.187.115:8000
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at Microsoft.AnalysisServices.AdomdClient.ASAzureUtility.PostHttpJsonData[TRequest,TResult](Uri uri, Dictionary`2 headers, TRequest requestObject, Int32 timeoutMs)
   at Microsoft.AnalysisServices.AdomdClient.ASAzureUtility.ResolvePaaSConnectionEndpointDetail(AsInstanceType asInstanceType, Uri dataSourceUri, String paasInfrastructureServerName, String restrictDatabaseName, Boolean premiumPublicXmlaEndpoint, TimeLeft& timeLeft, OnTimeoutAction timeoutAction, Guid parentActivityId)
   --- End of inner exception stack trace ---
   at Microsoft.AnalysisServices.AdomdClient.ASAzureUtility.ThrowConnectionException(WebException ex, AsInstanceType asInstanceType)
   at Microsoft.AnalysisServices.AdomdClient.ASAzureUtility.ResolvePaaSConnectionEndpointDetail(AsInstanceType asInstanceType, Uri dataSourceUri, String paasInfrastructureServerName, String restrictDatabaseName, Boolean premiumPublicXmlaEndpoint, TimeLeft& timeLeft, OnTimeoutAction timeoutAction, Guid parentActivityId)
   at Microsoft.AnalysisServices.AdomdClient.ConnectionInfo.ResolveHTTPConnectionPropertiesForPaaSInfrastructure(IConnectivityOwner owner, Uri& dataSourceUri, Boolean acquireAADToken, Boolean returnCloudConnectionAuthenticationProperties, String& paasCoreServerName, CloudConnectionAuthenticationProperties& cloudConnectionAuthenticationProperties)
   at Microsoft.AnalysisServices.AdomdClient.XmlaClient.OpenHttpConnection(ConnectionInfo connectionInfo, Boolean& isSessionTokenNeeded)
   at Microsoft.AnalysisServices.AdomdClient.XmlaClient.OpenConnection(ConnectionInfo connectionInfo, Boolean& isSessionTokenNeeded)
   at Microsoft.AnalysisServices.AdomdClient.XmlaClient.Connect(ConnectionInfo connectionInfo, Boolean beginSession)
   at Microsoft.AnalysisServices.AdomdClient.AdomdConnection.XmlaClientProvider.Connect(Boolean toIXMLA)
   at Microsoft.AnalysisServices.AdomdClient.AdomdConnection.ConnectToXMLA(Boolean createSession, Boolean isHTTP)
   at Microsoft.AnalysisServices.AdomdClient.AdomdConnection.Open()
   at ADOTabular.ADOTabularConnection.Open()
   at DaxStudio.UI.ViewModels.DocumentViewModel.SetupConnection(ConnectEvent message, ADOTabularConnection cnn)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback)
   at DaxStudio.UI.ViewModels.DocumentViewModel.<>c__DisplayClass263_0.<Handle>b__0()
   at System.Threading.Tasks.Task.Execute()
2020-07-27 14:53:15.508 +02:00 [Error] "DocumentViewModel" "Handle(ConnectEvent message)" "Unable to connect to the remote server"
Microsoft.AnalysisServices.AdomdClient.AdomdConnectionException: Unable to connect to the remote server ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 172.20.187.115:8000
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at Microsoft.AnalysisServices.AdomdClient.ASAzureUtility.PostHttpJsonData[TRequest,TResult](Uri uri, Dictionary`2 headers, TRequest requestObject, Int32 timeoutMs)
   at Microsoft.AnalysisServices.AdomdClient.ASAzureUtility.ResolvePaaSConnectionEndpointDetail(AsInstanceType asInstanceType, Uri dataSourceUri, String paasInfrastructureServerName, String restrictDatabaseName, Boolean premiumPublicXmlaEndpoint, TimeLeft& timeLeft, OnTimeoutAction timeoutAction, Guid parentActivityId)
   --- End of inner exception stack trace ---
   at Microsoft.AnalysisServices.AdomdClient.ASAzureUtility.ThrowConnectionException(WebException ex, AsInstanceType asInstanceType)
   at Microsoft.AnalysisServices.AdomdClient.ASAzureUtility.ResolvePaaSConnectionEndpointDetail(AsInstanceType asInstanceType, Uri dataSourceUri, String paasInfrastructureServerName, String restrictDatabaseName, Boolean premiumPublicXmlaEndpoint, TimeLeft& timeLeft, OnTimeoutAction timeoutAction, Guid parentActivityId)
   at Microsoft.AnalysisServices.AdomdClient.ConnectionInfo.ResolveHTTPConnectionPropertiesForPaaSInfrastructure(IConnectivityOwner owner, Uri& dataSourceUri, Boolean acquireAADToken, Boolean returnCloudConnectionAuthenticationProperties, String& paasCoreServerName, CloudConnectionAuthenticationProperties& cloudConnectionAuthenticationProperties)
   at Microsoft.AnalysisServices.AdomdClient.XmlaClient.OpenHttpConnection(ConnectionInfo connectionInfo, Boolean& isSessionTokenNeeded)
   at Microsoft.AnalysisServices.AdomdClient.XmlaClient.OpenConnection(ConnectionInfo connectionInfo, Boolean& isSessionTokenNeeded)
   at Microsoft.AnalysisServices.AdomdClient.XmlaClient.Connect(ConnectionInfo connectionInfo, Boolean beginSession)
   at Microsoft.AnalysisServices.AdomdClient.AdomdConnection.XmlaClientProvider.Connect(Boolean toIXMLA)
   at Microsoft.AnalysisServices.AdomdClient.AdomdConnection.ConnectToXMLA(Boolean createSession, Boolean isHTTP)
   at Microsoft.AnalysisServices.AdomdClient.AdomdConnection.Open()
   at ADOTabular.ADOTabularConnection.Open()
   at DaxStudio.UI.ViewModels.DocumentViewModel.SetupConnection(ConnectEvent message, ADOTabularConnection cnn)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback)
   at DaxStudio.UI.ViewModels.DocumentViewModel.<>c__DisplayClass263_0.<Handle>b__0()
   at System.Threading.Tasks.Task.Execute()
2020-07-27 14:54:21.048 +02:00 [Error] "DocumentViewModel" "Handle(ConnectEvent message)" "Unable to connect to the remote server"
Microsoft.AnalysisServices.AdomdClient.AdomdConnectionException: Unable to connect to the remote server ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 172.20.187.115:8000
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at Microsoft.AnalysisServices.AdomdClient.ASAzureUtility.PostHttpJsonData[TRequest,TResult](Uri uri, Dictionary`2 headers, TRequest requestObject, Int32 timeoutMs)
   at Microsoft.AnalysisServices.AdomdClient.ASAzureUtility.ResolvePaaSConnectionEndpointDetail(AsInstanceType asInstanceType, Uri dataSourceUri, String paasInfrastructureServerName, String restrictDatabaseName, Boolean premiumPublicXmlaEndpoint, TimeLeft& timeLeft, OnTimeoutAction timeoutAction, Guid parentActivityId)
   --- End of inner exception stack trace ---
   at Microsoft.AnalysisServices.AdomdClient.ASAzureUtility.ThrowConnectionException(WebException ex, AsInstanceType asInstanceType)
   at Microsoft.AnalysisServices.AdomdClient.ASAzureUtility.ResolvePaaSConnectionEndpointDetail(AsInstanceType asInstanceType, Uri dataSourceUri, String paasInfrastructureServerName, String restrictDatabaseName, Boolean premiumPublicXmlaEndpoint, TimeLeft& timeLeft, OnTimeoutAction timeoutAction, Guid parentActivityId)
   at Microsoft.AnalysisServices.AdomdClient.ConnectionInfo.ResolveHTTPConnectionPropertiesForPaaSInfrastructure(IConnectivityOwner owner, Uri& dataSourceUri, Boolean acquireAADToken, Boolean returnCloudConnectionAuthenticationProperties, String& paasCoreServerName, CloudConnectionAuthenticationProperties& cloudConnectionAuthenticationProperties)
   at Microsoft.AnalysisServices.AdomdClient.XmlaClient.OpenHttpConnection(ConnectionInfo connectionInfo, Boolean& isSessionTokenNeeded)
   at Microsoft.AnalysisServices.AdomdClient.XmlaClient.OpenConnection(ConnectionInfo connectionInfo, Boolean& isSessionTokenNeeded)
   at Microsoft.AnalysisServices.AdomdClient.XmlaClient.Connect(ConnectionInfo connectionInfo, Boolean beginSession)
   at Microsoft.AnalysisServices.AdomdClient.AdomdConnection.XmlaClientProvider.Connect(Boolean toIXMLA)
   at Microsoft.AnalysisServices.AdomdClient.AdomdConnection.ConnectToXMLA(Boolean createSession, Boolean isHTTP)
   at Microsoft.AnalysisServices.AdomdClient.AdomdConnection.Open()
   at ADOTabular.ADOTabularConnection.Open()
   at DaxStudio.UI.ViewModels.DocumentViewModel.SetupConnection(ConnectEvent message, ADOTabularConnection cnn)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback)
   at DaxStudio.UI.ViewModels.DocumentViewModel.<>c__DisplayClass263_0.<Handle>b__0()
   at System.Threading.Tasks.Task.Execute()
2020-07-27 14:57:03.463 +02:00 [Error] "DocumentViewModel" "Handle(ConnectEvent message)" "Unable to connect to the remote server"
Microsoft.AnalysisServices.AdomdClient.AdomdConnectionException: Unable to connect to the remote server ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 172.20.187.115:8000
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at Microsoft.AnalysisServices.AdomdClient.ASAzureUtility.PostHttpJsonData[TRequest,TResult](Uri uri, Dictionary`2 headers, TRequest requestObject, Int32 timeoutMs)
   at Microsoft.AnalysisServices.AdomdClient.ASAzureUtility.ResolvePaaSConnectionEndpointDetail(AsInstanceType asInstanceType, Uri dataSourceUri, String paasInfrastructureServerName, String restrictDatabaseName, Boolean premiumPublicXmlaEndpoint, TimeLeft& timeLeft, OnTimeoutAction timeoutAction, Guid parentActivityId)
   --- End of inner exception stack trace ---
   at Microsoft.AnalysisServices.AdomdClient.ASAzureUtility.ThrowConnectionException(WebException ex, AsInstanceType asInstanceType)
   at Microsoft.AnalysisServices.AdomdClient.ASAzureUtility.ResolvePaaSConnectionEndpointDetail(AsInstanceType asInstanceType, Uri dataSourceUri, String paasInfrastructureServerName, String restrictDatabaseName, Boolean premiumPublicXmlaEndpoint, TimeLeft& timeLeft, OnTimeoutAction timeoutAction, Guid parentActivityId)
   at Microsoft.AnalysisServices.AdomdClient.ConnectionInfo.ResolveHTTPConnectionPropertiesForPaaSInfrastructure(IConnectivityOwner owner, Uri& dataSourceUri, Boolean acquireAADToken, Boolean returnCloudConnectionAuthenticationProperties, String& paasCoreServerName, CloudConnectionAuthenticationProperties& cloudConnectionAuthenticationProperties)
   at Microsoft.AnalysisServices.AdomdClient.XmlaClient.OpenHttpConnection(ConnectionInfo connectionInfo, Boolean& isSessionTokenNeeded)
   at Microsoft.AnalysisServices.AdomdClient.XmlaClient.OpenConnection(ConnectionInfo connectionInfo, Boolean& isSessionTokenNeeded)
   at Microsoft.AnalysisServices.AdomdClient.XmlaClient.Connect(ConnectionInfo connectionInfo, Boolean beginSession)
   at Microsoft.AnalysisServices.AdomdClient.AdomdConnection.XmlaClientProvider.Connect(Boolean toIXMLA)
   at Microsoft.AnalysisServices.AdomdClient.AdomdConnection.ConnectToXMLA(Boolean createSession, Boolean isHTTP)
   at Microsoft.AnalysisServices.AdomdClient.AdomdConnection.Open()
   at ADOTabular.ADOTabularConnection.Open()
   at DaxStudio.UI.ViewModels.DocumentViewModel.SetupConnection(ConnectEvent message, ADOTabularConnection cnn)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback)
   at DaxStudio.UI.ViewModels.DocumentViewModel.<>c__DisplayClass263_0.<Handle>b__0()
   at System.Threading.Tasks.Task.Execute()

**Comment by dgosbell** [comment]
Are you able to provide more information on what software you are using for your proxy and how you have it configured?

Something appears to be confusing the Microsoft Adomdclient libraries into thinking it is connecting to ASAzure not an on-prem AS instance. So this may be a bug in those libraries, but I really don't have enough information about what is going on to know for sure.

I'm also not sure why you are trying to debug with fiddler as that would only capture http/s requests. Do you see anything in fiddler when using SSMS? Are you able to open a DAX window and execute DAX queries in SSMS or were you just connecting the object browser?

I'm not sure why you would be able to connect with SSMS and not DAX Studio, they should be using similar connection libraries. You could maybe try the latest 2.12 release as I have updated to the latest Microsoft libraries

**Comment by ElMiguel123** [comment]
Good afternoon, for your information the last version completely solve the issue. We've check on our side if the port of our proxy was well open (which was the case) but for a strange reason, in the previous version, we didn't receive the popup of Microsoft for the authentication.
Last version fix it :)
Thanks again

**Comment by dgosbell** [comment]
Great, thanks for letting me know. The only real change that might have affected this was that I've updated the Microsoft data providers so maybe they released an update for this. I'm glad it's working for you now
