### ISSUE TITLE
"The specified Power BI workspace is not found." When workspace name contains single quotation

### ISSUE THREAD

**Issue by Oddjobe** [DaxStudio/DaxStudio#434]
**Describe the bug**
I can connect, but I daxstudio 2.12.2 can't find the workspace

I tried different permutations
like 
"powerbi://api.powerbi.com/v1.0/myorg/XXXXXXX KPI's"
'powerbi://api.powerbi.com/v1.0/myorg/XXXXXXX KPI's'
powerbi://api.powerbi.com/v1.0/myorg/XXXXXXX KPI's
(powerbi://api.powerbi.com/v1.0/myorg/XXXXXXX KPI's)

This works fine in Tabular Editor & SSMS when wrapped in "<Workspace Connection>"

**Screenshots**
![image](https://user-images.githubusercontent.com/15087494/94871255-e1105600-0449-11eb-97cb-4d96f7a798e4.png)

**Errort**
2020-10-02 00:58:51.296 +02:00 [Error] "DocumentViewModel" "Handle(ConnectEvent message)" "The specified Power BI workspace is not found."
Microsoft.AnalysisServices.AdomdClient.AdomdConnectionException: The specified Power BI workspace is not found.
   at Microsoft.AnalysisServices.AdomdClient.ConnectionInfo.ResolveHTTPConnectionPropertiesForPaaSInfrastructure(IConnectivityOwner owner, Uri& dataSourceUri, Boolean acquireAADToken, Boolean returnCloudConnectionAuthenticationProperties, String& paasCoreServerName, CloudConnectionAuthenticationProperties& cloudConnectionAuthenticationProperties)
   at Microsoft.AnalysisServices.AdomdClient.XmlaClient.OpenHttpConnection(ConnectionInfo connectionInfo, Boolean& isSessionTokenNeeded)
   at Microsoft.AnalysisServices.AdomdClient.XmlaClient.OpenConnection(ConnectionInfo connectionInfo, Boolean& isSessionTokenNeeded)
   at Microsoft.AnalysisServices.AdomdClient.XmlaClient.Connect(ConnectionInfo connectionInfo, Boolean beginSession)
   at Microsoft.AnalysisServices.AdomdClient.AdomdConnection.XmlaClientProvider.Connect(Boolean toIXMLA)
   at Microsoft.AnalysisServices.AdomdClient.AdomdConnection.ConnectToXMLA(Boolean createSession, Boolean isHTTP)
   at Microsoft.AnalysisServices.AdomdClient.AdomdConnection.Open()
   at ADOTabular.ADOTabularConnection.Open()
   at DaxStudio.UI.ViewModels.DocumentViewModel.SetupConnection(ConnectEvent message, ADOTabularConnection cnn)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback)
   at DaxStudio.UI.ViewModels.DocumentViewModel.<>c__DisplayClass263_0.<Handle>b__0()
   at System.Threading.Tasks.Task.Execute()

**Comment by dgosbell** [comment]
Thanks for logging this, but I'm having issues reproducing the full issue.

If I use just `powerbi://api.powerbi.com/v1.0/myorg/XXXXXXX KPI's` when I connect I get an error, but the message is different. It says:

> Error Connecting: The property value containing the ''' character (at index 52 in the connection string) must be enclosed in quotation marks.


But if I use the version with double quotes "  that works with TE and SSMS eg. `"powerbi://api.powerbi.com/v1.0/myorg/XXXXXXX KPI's"` then I am able to connect without error using v2.12.2.

I think I can improve this so that DAX Studio will automatically quote the name if it needs to, but I'm not sure why you are getting a workspace not found error.

Are you able to re-try the version with double quotes? Maybe test in SSMS and if that works copy and paste the same server name into DAX Studio

**Comment by Oddjobe** [comment]
Hi Darren,
I tried again going through the following steps:

1. Connect via SSMS V.18.6 Works fine
![image](https://user-images.githubusercontent.com/15087494/94957254-baa3f680-04ed-11eb-88c3-60d5f2feda10.png)

2. Connect via TE Works fine
with "powerbi://api.powerbi.com/v1.0/myorg/XXXXXXX KPI's"

3. Copy connection string from other successful connections SSMS & TE still doesn't work.

**Comment by dgosbell** [comment]
That's really strange, I still cannot reproduce this at all. I was wondering if it was an order of operations thing where the workspace had been paged out of memory and the first client to connect got an error, but that then "woke" the workspace up. But even when I force something like that to happen I just get a longer pause before the connection succeeds.

I don't have any special workspace handling code in DAX Studio, that is all handled by the Microsoft AdomdClient library which I think is the same thing SSMS is using. And Daniel is doing a similar thing in Tabular Editor - he's just using the TOM library instead of AdomdClient, but they are both provided by Microsoft.

The only way I have found to trigger a "workspace not found" error is if I edit the name of the workspace to one that does not exist.

Are you able to try running the following script in PowerShell ISE and see if it works?

```
## change the following for your endpoint
$xmlaEndpoint = "powerbi://api.powerbi.com/v1.0/myorg/KPI's"

## you may need to change this path if you have install DAX Studio in a non-default location
[Reflection.Assembly]::LoadFile("C:\program files\dax studio\bin\Microsoft.AnalysisServices.AdomdClient.dll")
$connStr = "Data Source=""$xmlaEndpoint"""
$cnn = [Microsoft.AnalysisServices.AdomdClient.AdomdConnection]::new($connStr)
$cmd = $cnn.CreateCommand()
$cmd.CommandText = "SELECT * FROM `$SYSTEM.DBSCHEMA_CATALOGS"
$da = [Microsoft.AnalysisServices.AdomdClient.AdomdDataAdapter]::new($cmd)
$dt = [System.Data.DataTable]::new()
$da.Fill($dt)
# this will output a list of all the data sets in your workspace
$dt.Rows | ft

```

It should produce output like the following, this is from my test `KPI's` workspace where I just uploaded the Adventure Works sample pbix file. This is a simplified version of what DAX Studio is doing internally.

```
GAC    Version        Location                                                                                                                                           
---    -------        --------                                                                                                                                           
False  v4.0.30319     C:\program files\dax studio\bin\Microsoft.AnalysisServices.AdomdClient.dll                                                                         
1



CATALOG_NAME               DESCRIPTION ROLES DATE_MODIFIED          COMPATIBILITY_LEVEL TYPE VERSION DATABASE_ID                          DATABASE_GUID DATE_QUERIED
------------               ----------- ----- -------------          ------------------- ---- ------- -----------                          ------------- ------------
Adventure Works DW 2020 v2                   15/09/2020 11:04:29 PM                1520              a11440f8-8e28-43e8-bf4c-52911094de2f                           

```

**Comment by Oddjobe** [comment]
That worked, i was able to list the objects in the workspace successfully!
![image](https://user-images.githubusercontent.com/15087494/94988126-56c01300-056b-11eb-82de-23ee876ed41f.png)
