### ISSUE TITLE
Excel Addin Exceotuib

### ISSUE THREAD

**Issue by edhans** [DaxStudio/DaxStudio#509]
**Describe the bug**
After installing DAX Studio 14.0, then launching Excel, the addin doesn't work and will not load.

**To Reproduce**
1) Install DAX Studio with Excel Addin
2) Launch Excel

**Expected behavior**
It works.

**Screenshots**
![image](https://user-images.githubusercontent.com/45298358/104943885-3f1a6800-596b-11eb-91f3-dc8b49d1161c.png)

**Additional context**
Full text of the details box:
Name: 
From: file:///C:/Program Files/DAX Studio/bin/DaxStudio.vsto

************** Exception Text **************
System.Deployment.Application.InvalidDeploymentException: Exception reading manifest from file:///C:/Program%20Files/DAX%20Studio/bin/DaxStudio.dll.manifest: the manifest may not be valid or the file could not be opened. ---> System.Deployment.Application.InvalidDeploymentException: Parsing and DOM creation of the manifest resulted in error. Following parsing errors were noticed: 
			-HRESULT: 	0x80070c81
			 Start line: 	0
			 Start column: 	0
			 Host file: 	 ---> System.Runtime.InteropServices.COMException: Exception from HRESULT: 0x80070C81
   at System.Deployment.Internal.Isolation.IsolationInterop.CreateCMSFromXml(Byte[] buffer, UInt32 bufferSize, IManifestParseErrorCallback Callback, Guid& riid)
   at System.Deployment.Application.Manifest.AssemblyManifest.LoadCMSFromStream(Stream stream)
   --- End of inner exception stack trace ---
   at System.Deployment.Application.Manifest.AssemblyManifest.LoadCMSFromStream(Stream stream)
   at System.Deployment.Application.Manifest.AssemblyManifest..ctor(FileStream fileStream)
   at System.Deployment.Application.ManifestReader.FromDocument(String localPath, ManifestType manifestType, Uri sourceUri)
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.GetManifests(TimeSpan timeout)
   at Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.InstallAddIn()

**Comment by dgosbell** [comment]
Thanks for logging this Ed. It looks like we've hit a bug in msbuild that is generating the manifest file incorrectly. I've figured out a work around and will publish a new release shortly.

**Comment by dgosbell** [comment]
2.14.1 is now published
