### ISSUE TITLE
Add support for opening a file and connecting to a server and database using cmdline parameters

### ISSUE THREAD

**Issue by dgosbell** [DaxStudio/DaxStudio#612]
Currently when using the /f cmdline parameter the /s and /d parameters are ignored

**Describe the solution you'd like**
It should be possible to open a file and specify the server and database parameters as suggested in discussion #519

**Comment by dgosbell** [comment]
A preview build which supports passing a file, server name and database name at the same time is available on our build server at https://ci.appveyor.com/project/DarrenGosbell/daxstudio/build/artifacts 

eg.

`DaxStudio /f myfile.dax /s localhost /d "Adventure Works"`

**Comment by NickEPalmer** [comment]
Thanks for being so responsive and putting this change in. I'm testing it now and so far looks good.  

I did want to report that when I start DAX Studio from a command prompt after installing the preview build that I get the following exception.  DAX Studio comes up with no issues and seems to run ok.

C:\Program Files\DAX Studio>Could not load file or assembly 'AvalonDock.Themes.VS2013, Culture=neutral' or one of its dependencies. The system cannot find the file specified.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at System.Windows.Navigation.BaseUriHelper.GetLoadedAssembly(String assemblyName, String assemblyVersion, String assemblyKey)
   at MS.Internal.AppModel.ResourceContainer.GetResourceManagerWrapper(Uri uri, String& partName, Boolean& isContentFile)
   at MS.Internal.AppModel.ResourceContainer.GetPartCore(Uri uri)
   at System.IO.Packaging.Package.GetPartHelper(Uri partUri)
   at System.IO.Packaging.Package.GetPart(Uri partUri)
   at System.IO.Packaging.PackWebResponse.CachedResponse.GetResponseStream()
   at System.IO.Packaging.PackWebResponse.get_ContentType()
   at MS.Internal.WpfWebRequestHelper.GetContentType(WebResponse response)
   at MS.Internal.WpfWebRequestHelper.GetResponseStream(WebRequest request, ContentType& contentType)
   at System.Windows.ResourceDictionary.set_Source(Uri value)
   at MLib.Internal.AppearanceManagerImpl.SetThemeSourceAndAccentColor(List`1 sources, Color accentColor)
Could not load file or assembly 'AvalonDock.Themes.VS2013, Culture=neutral' or one of its dependencies. The system cannot find the file specified.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at System.Windows.Navigation.BaseUriHelper.GetLoadedAssembly(String assemblyName, String assemblyVersion, String assemblyKey)
   at MS.Internal.AppModel.ResourceContainer.GetResourceManagerWrapper(Uri uri, String& partName, Boolean& isContentFile)
   at MS.Internal.AppModel.ResourceContainer.GetPartCore(Uri uri)
   at System.IO.Packaging.Package.GetPartHelper(Uri partUri)
   at System.IO.Packaging.Package.GetPart(Uri partUri)
   at System.IO.Packaging.PackWebResponse.CachedResponse.GetResponseStream()
   at System.IO.Packaging.PackWebResponse.get_ContentType()
   at MS.Internal.WpfWebRequestHelper.GetContentType(WebResponse response)
   at MS.Internal.WpfWebRequestHelper.GetResponseStream(WebRequest request, ContentType& contentType)
   at System.Windows.ResourceDictionary.set_Source(Uri value)
   at MLib.Internal.AppearanceManagerImpl.SetThemeSourceAndAccentColor(List`1 sources, Color accentColor)

**Comment by dgosbell** [comment]
Thanks for letting me know about that. It's strange but it does not seem to throw that same error when I run in debug mode so I had not seen this. But I have been able find that reference and correct it. There is a build with this fix on the appveyor server here https://ci.appveyor.com/project/DarrenGosbell/daxstudio/builds/39121475/artifacts if you are interested

**Comment by alhowarth** [comment]
@dgosbell Was there ever a feature request added for the 2nd part of this?

"_Would it be possible to add a way to pass a DAX expression in addition to the AS server and database to DaxStudio via the command line_?

It probably would not be too hard to do this, but I'm not sure how we would pass the text back."

**Comment by dgosbell** [comment]
@alhowarth Do you mean the bit about passing text back? 

If so the person that asked this previously is doing this using a file. They write out their DAX to a .dax file, pass the server, database and file on the command line. Then when the user saves the file and closes DAX Studio they read the contents of the file to pick up any changes.

**Comment by alhowarth** [comment]
@dgosbell 

Yes, passing text out.  We are looking for a method of unit testing Power BI/DAX queries.  We were wondering if there was a way to call DAXStudio from a command-line and have DAXStudio pass success or failure, either in a file or something that Jenkins could pickup.

**Comment by dgosbell** [comment]
@alhowarth -yes so this has also recently come up in conversation #519 - I have a few ideas around adding support for command line options and maybe some unit testing scenarios (eg asserting against an expected scalar value or a file). And as part of this I would return a non-zero exit code for failed tests and write out information about the failure. But this is all just conceptual at the moment.
