### ISSUE TITLE
DaxStudio Not Loading after Install

### ISSUE THREAD

**Issue by akajiuwa** [DaxStudio/DaxStudio#750]
I have just installed the latest version of DaxStudio but I am not able to Launch the application.

I have tried Launching it directly as myself, as Admin and via the External Tools ribbon in Power BI all without success.
Machine Details
![image](https://user-images.githubusercontent.com/29633519/139673235-29efe348-6561-4b5b-b40d-e9de95352563.png)

See Log Content below

2021-11-01 12:40:31.398 +00:00 [ERR] SystemInfo GetOSInfo Error getting OS name and version Info: Invalid class 
System.Management.ManagementException: Invalid class 
   at System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
   at System.Management.ManagementObjectCollection.ManagementObjectEnumerator.MoveNext()
   at DaxStudio.UI.Utils.SystemInfo.GetOSInfo()
2021-11-01 12:40:31.445 +00:00 [ERR] SystemInfo GetOSInfo Error getting OS memory Info: Invalid class 
System.Management.ManagementException: Invalid class 
   at System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
   at System.Management.ManagementObjectCollection.ManagementObjectEnumerator.MoveNext()
   at DaxStudio.UI.Utils.SystemInfo.GetOSInfo()
2021-11-01 12:40:31.445 +00:00 [INF] DAX STUDIO VERSION: 2.16.2.632
2021-11-01 12:40:31.445 +00:00 [INF] System Info: OSCaption = null
2021-11-01 12:40:31.445 +00:00 [INF] System Info: OSRelease = 2009
2021-11-01 12:40:31.445 +00:00 [ERR] EntryPoint LogFatalCrash DAX Studio Standalone CurrentDomainOnUnhandledException
System.NullReferenceException: Object reference not set to an instance of an object.
   at DaxStudio.UI.Utils.SystemInfo.WriteToLog()
   at DaxStudio.Standalone.EntryPoint.ConfigureLogging(LoggingLevelSwitch levelSwitch)
   at DaxStudio.Standalone.EntryPoint.Main()

Fabian

**Comment by dgosbell** [comment]
Thanks for logging this. At startup I write out some basic system information to the log to assist in debugging issues, but it looks like the Windows system I query to get this information (WMI) might have some sort of corruption on your machine. However this information is not needed for the actual operation of DAX Studio so I've improved the error handling around this startup logging so that it should be able to continue normal operation even if it hits this sort of issue. 

I have a preview build that includes the improved error handling here:
https://ci.appveyor.com/project/DarrenGosbell/daxstudio/builds/41368710/artifacts

Are you able to test using either the installer or the portable version and see if this fixes your issue as I am not able to reproduce this crash on any of the machines I have access to?

**Comment by akajiuwa** [comment]
Hi Darren,

I have used the preview version of the installer and this time DAX studio successfully launches but cannot connect to the model I have open.
This is what I see when i try connecting to the pbix file directly
![image](https://user-images.githubusercontent.com/29633519/139819561-5100bd3f-66c5-40b7-b995-602ab56d75f6.png)

This is the message i get when i try launching via the external tools ribbon
![image](https://user-images.githubusercontent.com/29633519/139819827-afb761a1-c399-4b7b-afc4-030a70689903.png)

**See log entry below**

2021-11-02 09:22:25.995 +00:00 [ERR] SystemInfo GetOSInfo Error getting OS name and version Info: Invalid class 
System.Management.ManagementException: Invalid class 
   at System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
   at System.Management.ManagementObjectCollection.ManagementObjectEnumerator.MoveNext()
   at DaxStudio.UI.Utils.SystemInfo.GetOSInfo()
2021-11-02 09:22:26.065 +00:00 [ERR] SystemInfo GetOSInfo Error getting OS memory Info: Invalid class 
System.Management.ManagementException: Invalid class 
   at System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
   at System.Management.ManagementObjectCollection.ManagementObjectEnumerator.MoveNext()
   at DaxStudio.UI.Utils.SystemInfo.GetOSInfo()
2021-11-02 09:22:26.071 +00:00 [INF] DAX STUDIO VERSION: 2.16.3.663
2021-11-02 09:22:26.071 +00:00 [INF] System Info: OSCaption = null
2021-11-02 09:22:26.073 +00:00 [INF] System Info: OSRelease = 2009
2021-11-02 09:22:26.074 +00:00 [INF] System Info: OSVersion = 0.0
2021-11-02 09:22:26.074 +00:00 [INF] System Info: OSArchitecture = null
2021-11-02 09:22:26.074 +00:00 [INF] System Info: VisibleMemoryGB = 0.00
2021-11-02 09:22:26.074 +00:00 [INF] System Info: FreeMemoryGB = 0.00
2021-11-02 09:22:26.074 +00:00 [INF] Culture Info: Name = en-GB
2021-11-02 09:22:26.079 +00:00 [INF] Culture Info: DisplayName = English (United Kingdom)
2021-11-02 09:22:26.079 +00:00 [INF] Culture Info: EnglishName = English (United Kingdom)
2021-11-02 09:22:26.079 +00:00 [INF] Culture Info: 2-Letter ISO Name = en
2021-11-02 09:22:26.079 +00:00 [INF] Culture Info: DecimalSeparator = .
2021-11-02 09:22:26.079 +00:00 [INF] Culture Info: GroupSeparator = ,
2021-11-02 09:22:26.079 +00:00 [INF] Culture Info: CurrencySymbol = £
2021-11-02 09:22:26.080 +00:00 [INF] Culture Info: ShortDatePattern = dd/MM/yyyy
2021-11-02 09:22:26.083 +00:00 [INF] CommandLine Args: ["C:\\Program Files\\DAX Studio\\DaxStudio.exe","/server=localhost:49882","/database=ce107cd7-3d21-42b8-ba49-5f7506f4cd17"]
2021-11-02 09:22:26.085 +00:00 [INF] Portable Mode: False
2021-11-02 09:22:26.085 +00:00 [INF] Changing minimum log event to Warning
2021-11-02 09:22:31.117 +00:00 [ERR] ProcessExtensions GetParent Error getting parent processid via WMI: Invalid class 
System.Management.ManagementException: Invalid class 
   at System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
   at System.Management.ManagementObjectCollection.ManagementObjectEnumerator.MoveNext()
   at System.Linq.Enumerable.<OfTypeIterator>d__95`1.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at DaxStudio.UI.Extensions.ProcessExtensions.GetParent(Process process)
2021-11-02 09:22:31.119 +00:00 [WRN] PowerBIInstance ctor Unable to find ' - ' in Power BI title 'localhost:0' -1
2021-11-02 09:22:31.645 +00:00 [ERR] DocumentViewModel UpdateConnections The following error occurred while updating the connection: The given path's format is not supported.
System.NotSupportedException: The given path's format is not supported.
   at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
   at System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean checkForDuplicates, Boolean needFullPath)
   at System.IO.FileInfo.Init(String fileName, Boolean checkHost)
   at ADOTabular.ADOTabularConnection.set_FileName(String value)
   at DaxStudio.UI.Model.ConnectionManager.Connect(ConnectEvent message)
   at DaxStudio.UI.ViewModels.DocumentViewModel.UpdateConnections(ConnectEvent message)

Fabian

**Comment by dgosbell** [comment]
What is the name of your PBIX file? According to the screenshot and the log messages either your file is called 'localhost:0' or you have some dialog box open in Power BI Desktop that has that as a title. If you have some dialog open then you should close that. I cannot reproduce this issue since I cannot save a file called 'localhost:0' since it is not valid to include a colon (:) character in a filename. So I'm not sure how you got into this state.

**Comment by akajiuwa** [comment]
The pbix is named **Sales Data**
I have rebooted my machine a couple of times and at the moment all i have open is same pbix file and Dax Studio. I have never come across this issue as well and I have been using Dax Studio for several years now.

The reference to localhost is the only option in the dropdown. It is quite strange. 

Fabian

**Comment by akajiuwa** [comment]
I have manually replaced the port number with the one displayed in the taskbar as a Tabular Server connection and successfully connected but the default PBI/SSDT Model or connecting from External Tools Ribbon still throw an error.

At least I can still manually connect, maybe it is something local to this machine as I only started using this laptop a couple of days ago. I don't have this issue when I am using my alternate laptop.


Fabian

**Comment by dgosbell** [comment]
OK, so I think I've found how that "localhost:0" is getting generated, but that should only happen if there is no parent process for the msmdsrv process. And in theory that should not be possible, this process should always be a child process of the PBIDesktop.exe process.

I've added some extra checks that should enable you to use the External tools ribbon in Power BI Desktop on that problematic laptop. Can you test the following build and see if that works around this issue?
https://ci.appveyor.com/project/DarrenGosbell/daxstudio/builds/41387499/artifacts

**Comment by jesusdeblasgarcia** [comment]
In my case, also, DAX Studio didn´t launch but using the mentioned preview build  it works. Thanks.

**Comment by akajiuwa** [comment]
Apologies for the delay in responding, After installing _adding error handling around setting short filename 2.16.3.664 build
_ I am  able to connect using the ribbon. Thanks for looking into this and providing a solution that works.

**Comment by dgosbell** [comment]
This fix is now incorporated into the current 2.17.2 release

**Comment by akajiuwa** [comment]
Downloaded and installed 2.17.2 and all is good.
