### ISSUE TITLE
Excel add-in not loading

### ISSUE THREAD

**Issue by tmsvl** [DaxStudio/DaxStudio#865]
Hi,

I've tried installing DAX Studio several times (all users - all components checked - both run as administrator or under normal user), but whatever I do, I can't get the Excel plugin to show up.

In DAX Studio Checker, I see this at the bottom:

```
Checking Excel Add-in
    Detected Excel Version: 16 - Excelv16
    Excel Path: 

FATAL ERROR:
Empty path name is not legal.
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at DaxStudio.CheckerApp.Checker.GetMachineType(String fileName)
   at DaxStudio.CheckerApp.Checker.GetExcelDetails()
   at DaxStudio.CheckerApp.Checker.CheckExcelAddin()
   at DaxStudio.CheckerApp.MainWindow.OnLoaded(Object sender, RoutedEventArgs e)
```

It looks like it cannot detect my Excel path somehow?

**Comment by dgosbell** [comment]
That's a bit strange, but we don't technically need the Excel path to run I just use that in the checker to figure out if it's 32 or 64 bit Excel.

When you go to File > Options > Addins then change the "Manage" dropdown to "COM Add-ins" and click GO do you see "DAX Studio Excel Addin" in the list and is it ticked?

If so can you follow the instructions here to create an Excel diagnostic log and then post it to this issue on github https://daxstudio.org/documentation/troubleshooting/logging-settings/

**Comment by rafaeljosem** [comment]
Hello,

I've got the same issue and the Dax Studio Checker says the same thing about a path being empty.

I went to the "COM Add-ins" dialog box and the Dax Studio Addin is not event listed there.

I already tried reinstalling Dax Studio and problem persists.

Thanks

**Comment by rafaeljosem** [comment]
Hello,

I managed to activate the plugin in excel by double clicking the DaxStudio.vsto file in the bin directory.

Now, when I click the "Dax Studio" button it showns the following error:  "Excel Addin is unable to launch the Dax Studio User Interface".

Here's the excel log file:

```
2022-07-26 19:36:18.037 -04:00 [INF] ============ Excel Add-in Startup =============
2022-07-26 19:36:18.051 -04:00 [INF] Excel Version: 16.0
2022-07-26 19:36:18.053 -04:00 [INF] Excel Build: 15330
2022-07-26 19:36:18.056 -04:00 [INF] Excel Operating System: Windows (64-bit) NT 10.00
2022-07-26 19:36:18.064 -04:00 [INF]    Addin : DaxStudio Excel Addin Loaded: True
2022-07-26 19:36:18.064 -04:00 [INF]    Addin : Microsoft Power Map for Excel Loaded: True
2022-07-26 19:36:18.064 -04:00 [INF]    Addin : LogiOptionsExcelAddin Loaded: True
2022-07-26 19:36:18.065 -04:00 [INF]    Addin : Microsoft Data Streamer for Excel Loaded: True
2022-07-26 19:36:18.065 -04:00 [INF]    Addin : Acrobat PDFMaker Office COM Addin Loaded: True
2022-07-26 19:36:18.065 -04:00 [INF]    Addin : Microsoft Power Pivot for Excel Loaded: True
2022-07-26 19:36:18.065 -04:00 [INF] Logging enabled by Shift Key at startup
2022-07-26 19:36:25.043 -04:00 [DBG] DaxStudioRibbon Launch Entering Launch()
2022-07-26 19:36:25.078 -04:00 [INF] WebHost Start DaxStudio Host starting on port 9000
2022-07-26 19:36:25.236 -04:00 [DBG] Startup Configuration Starting OWIN configuration
2022-07-26 19:36:25.290 -04:00 [ERR] Startup Configuration No se puede cargar el archivo o ensamblado 'System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ni una de sus dependencias. El sistema no puede encontrar el archivo especificado.
2022-07-26 19:36:25.290 -04:00 [DBG] Startup Configuration Finished OWIN configuration
2022-07-26 19:36:25.327 -04:00 [INF] WebHost Start DaxStudio Host started on port 9000
2022-07-26 19:36:25.327 -04:00 [DBG] DaxStudioRibbon Launch Checking for an existing instance of DaxStudio.exe
2022-07-26 19:36:31.997 -04:00 [DBG] DaxStudioRibbon Launch Entering Launch()
2022-07-26 19:36:31.997 -04:00 [DBG] DaxStudioRibbon Launch Checking for an existing instance of DaxStudio.exe
2022-07-26 19:36:33.439 -04:00 [ERR] DaxStudioRibbon BtnDaxClick Excel Addin is unable to launch the DAX Studio User Interface    en DaxStudio.ExcelAddin.DaxStudioRibbon.Launch(Boolean enableLogging)
   en DaxStudio.ExcelAddin.DaxStudioRibbon.BtnDaxClick(Object sender, RibbonControlEventArgs e)
System.IO.FileNotFoundException: Excel Addin is unable to launch the DAX Studio User Interface
   en DaxStudio.ExcelAddin.DaxStudioRibbon.Launch(Boolean enableLogging)
   en DaxStudio.ExcelAddin.DaxStudioRibbon.BtnDaxClick(Object sender, RibbonControlEventArgs e)
2022-07-26 19:36:44.753 -04:00 [DBG] DaxStudioRibbon Launch Entering Launch()
2022-07-26 19:36:44.753 -04:00 [DBG] DaxStudioRibbon Launch Checking for an existing instance of DaxStudio.exe
2022-07-26 19:36:46.062 -04:00 [ERR] DaxStudioRibbon BtnDaxClick Excel Addin is unable to launch the DAX Studio User Interface    en DaxStudio.ExcelAddin.DaxStudioRibbon.Launch(Boolean enableLogging)
   en DaxStudio.ExcelAddin.DaxStudioRibbon.BtnDaxClick(Object sender, RibbonControlEventArgs e)
System.IO.FileNotFoundException: Excel Addin is unable to launch the DAX Studio User Interface
   en DaxStudio.ExcelAddin.DaxStudioRibbon.Launch(Boolean enableLogging)
   en DaxStudio.ExcelAddin.DaxStudioRibbon.BtnDaxClick(Object sender, RibbonControlEventArgs e)
2022-07-26 19:36:52.542 -04:00 [INF] ============ Excel Add-in Shutdown =============
2022-07-26 19:36:52.544 -04:00 [DBG] DaxStudioRibbon DaxStudioRibbon_Close Entering
2022-07-26 19:36:52.545 -04:00 [INF] DaxStudio Host stopped listening on port 9000
2022-07-26 19:36:52.550 -04:00 [DBG] DaxStudioRibbon DaxStudioRibbon_Close Exiting
```

Also, went to the Dax Studio Checker and I still see the error about a path not being found.

Thanks

**Comment by SergeiStPete** [comment]
Same with me, was able to activate it only by running DaxStudio.vsto. However, DAX Studio can't connect to the model on latest Excel Beta (Microsoft® Excel® for Microsoft 365 MSO (Version 2208 Build 16.0.15522.20000) 64-bit ). No such problem on other channels. It looks like Microsoft is changing something in Power Pivot.

**Comment by Masorah** [comment]
I had the same problem.
DAX Studio can not connect the Power Povit model when i activate it by Excel Add-in.
There is no problem when it activated by Power BI Desktop. 
My Excel versions is 2207 Build 15407.20000.
It's a Beta versions too.

**Comment by dgosbell** [comment]
@SergeiStPete and @Masorah I think your issue completely different. I've had another report via email with an error log and it looks like Microsoft have changed something in the Beta version. I do not have access to the Beta so I cannot check this, but it seems to be related to some changes in the Beta version.

@rafaeljosem - how did you install DAX Studio? Did you install for All Users or Current User or are you using the portable version?

**Comment by SergeiStPete** [comment]
@dgosbell , yes, exactly - Microsoft is changing data model architecture. Of course I don't know for sure, only my guess. Same problem was about a month ago. Not only DAX Studio didn't connect, data model was not opened by Data->"Manage data model" in Excel ribbon. Microsoft fixed that, both worked. But with latest updates icon works, DAX Studio not. As for the installation I was able to install update only the same way as @rafaeljosem did, i.e. by double click on daxstudio.vsto.
As a comment, MonkeyTool by Ken Puls is still working, here is no problems with connection.

**Comment by rafaeljosem** [comment]
@dgosbell I used the .exe file and installed it for all users as well as for me only. With both options won't work.

**Comment by Masorah** [comment]
@dgosbell 
Thank you sir!
I think it caused by beta version.

**Comment by dgosbell** [comment]
closing old issue
