### ISSUE TITLE
External component has thrown an exception.

### ISSUE THREAD

**Issue by pranamg** [DaxStudio/DaxStudio#919]
**Describe the bug**
I installed DAX Studio 3 on my laptop and I got the above error **External component has thrown an exception.**.

**To Reproduce**
1. Install DAX Studio 3 on a laptop you have already installed DAX Studio 2.17.3 (as part of Power BI Tips Business Ops 3.0.4).
2. Click on **Power BI Desktop** icon on Windows Start Menu
3. Power BI Desktop loads, and an error message popups up - **Error Message: External component has thrown an exception.** with a link to report the error to Microsoft.
4. Click on report the error to Microsoft and Power BI Desktop quits.
5. Search for **Add/remove programs** in Windows Search and the search for **DAX Studio** from the list of Programs.
6. Click on Uninstall.
7. Click on **Power BI Desktop** icon on Windows Start Menu to open Power BI Desktop open without any error messages or crashes.

**Expected behavior**
If you install DAX Studio 3 when you already have DAX Studio 2.17.3 installed in your system, your Power BI Desktop will throw up the error **External component has thrown an exception.** and then quit.

**Additional context**
Error message Details if it helps.
```
Feedback Type:
Frown (Error)

Error Message:
External component has thrown an exception.

Stack Trace:
System.Runtime.InteropServices.SEHException
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Form.ShowDialog(IWin32Window owner)
   at Microsoft.Mashup.Client.UI.Shared.WindowManager.ShowModal[T](T dialog, Func`1 showModalFunction)
   at Microsoft.PowerBI.Client.Program.<>c__DisplayClass4_1.<Main>b__2()
   at Microsoft.PowerBI.Client.Windows.IExceptionHandlerExtensions.<>c__DisplayClass3_0.<HandleExceptionsWithNestedTasks>b__0()
   at Microsoft.Mashup.Host.Document.ExceptionHandlerExtensions.HandleExceptions(IExceptionHandler exceptionHandler, Action action)

Stack Trace Message:
External component has thrown an exception.

Invocation Stack Trace:
   at Microsoft.Mashup.Host.Document.ExceptionExtensions.GetCurrentInvocationStackTrace()
   at Microsoft.Mashup.Client.UI.Shared.StackTraceInfo..ctor(String exceptionStackTrace, String invocationStackTrace, String exceptionMessage)
   at Microsoft.PowerBI.Client.Windows.Telemetry.PowerBIUserFeedbackServices.GetStackTraceInfo(Exception e)
   at Microsoft.PowerBI.Client.Windows.Telemetry.PowerBIUserFeedbackServices.ReportException(IWindowHandle activeWindow, IUIHost uiHost, FeedbackPackageInfo feedbackPackageInfo, Exception e, Boolean useGDICapture)
   at Microsoft.Mashup.Client.UI.Shared.UnexpectedExceptionHandler.<>c__DisplayClass14_0.<HandleException>b__0()
   at Microsoft.Mashup.Host.Document.SynchronizationContextExtensions.<>c__DisplayClass2_1.<SendAndMarshalExceptions>b__0(Object null)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at System.Windows.Forms.WindowsFormsSynchronizationContext.Send(SendOrPostCallback d, Object state)
   at Microsoft.Mashup.Host.Document.SynchronizationContextExtensions.SendAndMarshalExceptions(SynchronizationContext context, Action callback)
   at Microsoft.Mashup.Client.UI.Shared.UnexpectedExceptionHandler.HandleException(Exception e)
   at Microsoft.PowerBI.Client.PowerBIUnexpectedExceptionHandler.HandleException(Exception e)
   at Microsoft.Mashup.Host.Document.ExceptionHandlerExtensions.HandleExceptions(IExceptionHandler exceptionHandler, Action action)
   at Microsoft.PowerBI.Client.Program.Main(String[] args)


Error Code:
-2147467259 (0x80004005)

PowerBINonFatalError:
{"AppName":"PBIDesktop","AppVersion":"2.108.997.0","ModuleName":"Microsoft.Mashup.Client.UI.dll","Component":"Microsoft.Mashup.Client.UI.Shared.WindowManager","Error":"System.Runtime.InteropServices.SEHException","MethodDef":"ShowModal","ErrorOffset":"46"}

PowerBIUserFeedbackServices_IsReported:
True
```

**Comment by dgosbell** [comment]
Thanks for reporting this. However, I'm certain that the installation of DAX Studio was just a coincidence. There is absolutely no code in DAX Studio that executes when Power BI Desktop starts up. You can verify this by looking at the stack traces and observing that there are no calls to any code that starts with a "DaxStudio" class name. This error is something to do with a crash in the Mashup Client which is the internal code name for the Power Query engine. You need to report this issue to Microsoft if it keeps happening.
