### ISSUE TITLE
View Metrics does not work in DAX Studio 3.0.0

### ISSUE THREAD

**Issue by NickCodesDotNET** [DaxStudio/DaxStudio#926]
Upon clicking on "View Metrics" button I am getting the following 2 errors:

1) Error viewing metrics with ReadStatisticsFromData enabled (retry without statistics): The specified column was not found in the context at line 8, column 5.

2) Error viewing metrics: The specified column was not found in the context at line 8, column 5.

Error # 1 could be mitigated by dis-selecting "Read statistics from data" in the advanced options but error # 2 keeps being thrown. 

These error are connected to the server I am working on I am absolutely sure because I do not get any errors when I working on my other box. 

Error happens on this machine only:  
Microsoft SQL Server 2017 14.0.3445.2 (X64)  / Windows Server 2019 Standard 10.0 <X64> (Build 17763: ) (Hypervisor) 

**INTERESTINGLY! When I downgraded to DAX Studio 2.17.3 the problem disappeared, and I was able to view metrics. 

Here is LOG data: 
 
2022-09-06 16:20:05.179 -04:00 [INF] DAX STUDIO VERSION: 3.0.0.725
2022-09-06 16:20:05.230 -04:00 [INF] System Info: OSCaption = Microsoft Windows Server 2019 Standard
2022-09-06 16:20:05.231 -04:00 [INF] System Info: OSRelease = 1809
2022-09-06 16:20:05.231 -04:00 [INF] System Info: OSVersion = 10.0.17763
2022-09-06 16:20:05.231 -04:00 [INF] System Info: OSArchitecture = 64-bit
2022-09-06 16:20:05.231 -04:00 [INF] System Info: VisibleMemoryGB = 256.00
2022-09-06 16:20:05.231 -04:00 [INF] System Info: FreeMemoryGB = 50.25
2022-09-06 16:20:05.231 -04:00 [INF] Culture Info: Name = en-US
2022-09-06 16:20:05.235 -04:00 [INF] Culture Info: DisplayName = English (United States)
2022-09-06 16:20:05.235 -04:00 [INF] Culture Info: EnglishName = English (United States)
2022-09-06 16:20:05.235 -04:00 [INF] Culture Info: 2-Letter ISO Name = en
2022-09-06 16:20:05.236 -04:00 [INF] Culture Info: DecimalSeparator = .
2022-09-06 16:20:05.236 -04:00 [INF] Culture Info: GroupSeparator = ,
2022-09-06 16:20:05.236 -04:00 [INF] Culture Info: CurrencySymbol = $
2022-09-06 16:20:05.236 -04:00 [INF] Culture Info: ShortDatePattern = M/d/yyyy
2022-09-06 16:20:05.236 -04:00 [INF] CommandLine Args: ["C:\\Program Files\\DAX Studio\\DaxStudio.exe"]
2022-09-06 16:20:05.242 -04:00 [INF] Portable Mode: False
2022-09-06 16:20:05.242 -04:00 [INF] Changing minimum log event to Warning
2022-09-06 16:20:15.260 -04:00 [WRN] DocumentViewModel ViewAnalysisData Error loading VPA view with ReadStatisticsFromData enabled: The specified column was not found in the context at line 8, column 5.
Microsoft.AnalysisServices.AdomdClient.AdomdErrorResponseException: The specified column was not found in the context at line 8, column 5.
   at Microsoft.AnalysisServices.AdomdClient.XmlaClient.CheckForSoapFault(XmlReader reader, XmlaResult xmlaResult, Boolean throwIfError)
   at Microsoft.AnalysisServices.AdomdClient.XmlaClient.CheckForError(XmlReader reader, XmlaResult xmlaResult, Boolean throwIfError)
   at Microsoft.AnalysisServices.AdomdClient.XmlaClient.SendMessage(Boolean endReceivalIfException, Boolean readSession, Boolean readNamespaceCompatibility)
   at Microsoft.AnalysisServices.AdomdClient.XmlaClient.ExecuteStatement(String statement, IDictionary connectionProperties, IDictionary commandProperties, IDataParameterCollection parameters, Boolean isMdx)
   at Microsoft.AnalysisServices.AdomdClient.AdomdConnection.XmlaClientProvider.Microsoft.AnalysisServices.AdomdClient.IExecuteProvider.ExecuteTabular(CommandBehavior behavior, ICommandContentProvider contentProvider, AdomdPropertyCollection commandProperties, IDataParameterCollection parameters)
   at Microsoft.AnalysisServices.AdomdClient.AdomdCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.AnalysisServices.AdomdClient.AdomdCommand.System.Data.IDbCommand.ExecuteReader()
   at Dax.Metadata.Extractor.DmvExtractor.PopulateModel()
   at Dax.Metadata.Extractor.DmvExtractor.PopulateFromDmv(Model daxModel, IDbConnection connection, String serverName, String databaseName, String extractorApp, String extractorVersion)
   at Dax.Metadata.Extractor.TomExtractor.GetDaxModel(String serverName, String databaseName, String applicationName, String applicationVersion, Boolean readStatisticsFromData, Int32 sampleRows, Boolean analyzeDirectQuery)
   at DaxStudio.UI.ViewModels.DocumentViewModel.ViewAnalysisData()
2022-09-06 16:20:15.382 -04:00 [ERR] DocumentViewModel ViewAnalysisData Error Getting Metrics
Microsoft.AnalysisServices.AdomdClient.AdomdErrorResponseException: The specified column was not found in the context at line 8, column 5.
   at Microsoft.AnalysisServices.AdomdClient.XmlaClient.CheckForSoapFault(XmlReader reader, XmlaResult xmlaResult, Boolean throwIfError)
   at Microsoft.AnalysisServices.AdomdClient.XmlaClient.CheckForError(XmlReader reader, XmlaResult xmlaResult, Boolean throwIfError)
   at Microsoft.AnalysisServices.AdomdClient.XmlaClient.SendMessage(Boolean endReceivalIfException, Boolean readSession, Boolean readNamespaceCompatibility)
   at Microsoft.AnalysisServices.AdomdClient.XmlaClient.ExecuteStatement(String statement, IDictionary connectionProperties, IDictionary commandProperties, IDataParameterCollection parameters, Boolean isMdx)
   at Microsoft.AnalysisServices.AdomdClient.AdomdConnection.XmlaClientProvider.Microsoft.AnalysisServices.AdomdClient.IExecuteProvider.ExecuteTabular(CommandBehavior behavior, ICommandContentProvider contentProvider, AdomdPropertyCollection commandProperties, IDataParameterCollection parameters)
   at Microsoft.AnalysisServices.AdomdClient.AdomdCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.AnalysisServices.AdomdClient.AdomdCommand.System.Data.IDbCommand.ExecuteReader()
   at Dax.Metadata.Extractor.DmvExtractor.PopulateModel()
   at Dax.Metadata.Extractor.DmvExtractor.PopulateFromDmv(Model daxModel, IDbConnection connection, String serverName, String databaseName, String extractorApp, String extractorVersion)
   at Dax.Metadata.Extractor.TomExtractor.GetDaxModel(String serverName, String databaseName, String applicationName, String applicationVersion, Boolean readStatisticsFromData, Int32 sampleRows, Boolean analyzeDirectQuery)
   at DaxStudio.UI.ViewModels.DocumentViewModel.ViewAnalysisData()

**Comment by dgosbell** [comment]
This looks like the same issue as #887 I think this will be fixed in the next release. If you want to help test this you could try a preview of the next release here https://ci.appveyor.com/project/DarrenGosbell/daxstudio/build/artifacts

**Comment by dgosbell** [comment]
this should now be fixed in the 3.0.1 update

**Comment by NickCodesDotNET** [comment]
@dgosbell  Yes, it works. I just checked. Thank you
